kind: Service
apiVersion: v1
metadata:
  name: strimzi-canary
  labels:
    app: strimzi-canary
  namespace: kafka-ns
spec:
  ports:
    - port: 8080
      name: http
      protocol: TCP
      targetPort: 8080
  selector:
    app: strimzi-canary
