apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hubot-k8s-role
rules:
  - apiGroups:
      - ''
    resources:
      - pods
      - pods/log
      - events
    verbs:
      - get
      - list
      - watch
      - delete
  - apiGroups:
      - ''
    resources:
      - pods/exec
    verbs:
      - create
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - verbs:
      - get
      - patch
      - update
    apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkas
