kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hubot-k8s-role-rb
  namespace: kafka-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hubot-k8s-role
subjects:
  - kind: ServiceAccount
    name: hubot-sa
    namespace: hubot-ns
