apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/redis-enterprise-operator-cert.hubot-ns: ""
  name: redis-enterprise-operator-cert
  namespace: hubot-ns
spec:
  channel: production
  installPlanApproval: Automatic
  name: redis-enterprise-operator-cert
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: redis-enterprise-operator.v6.2.10-4
