apiVersion: app.redislabs.com/v1
kind: RedisEnterpriseCluster
metadata:
  name: redis-cluster
  namespace: hubot-ns
spec:
  nodes: 1
  persistentSpec:
    enabled: true
    storageClassName: managed-nfs-storage
    volumeSize: 20Gi
  redisEnterpriseImageSpec:
    imagePullPolicy: IfNotPresent
    repository: redislabs/redis
    versionTag: 6.2.10-90.rhel7-openshift
  redisEnterpriseNodeResources:
    limits:
      cpu: 4000m
      memory: 4Gi
    requests:
      cpu: 4000m
      memory: 4Gi
  uiServiceType: ClusterIP
  username: redisadmin@chatopsdemo.com
