apiVersion: v1
kind: Service
metadata:
  name: grafana-image-renderer
  labels:
    app.kubernetes.io/name: grafana-image-renderer
    app.kubernetes.io/component: renderer
  namespace: grafana-ns
spec:
  selector:
    app.kubernetes.io/name: grafana-image-renderer
    app.kubernetes.io/component: renderer
  ports:
    - protocol: TCP
      name: renderer
      port: 8081
      targetPort: renderer
