apiVersion: v1
kind: Secret
metadata:
  name: grafana-rendering-conf
  namespace: grafana-ns
stringData:
  #GF_INSTALL_PLUGINS: "grafana-polystat-panel 1.2.5, marcusolsson-hexmap-panel 0.2.0"
  GF_RENDERING_SERVER_URL: http://grafana-image-renderer:8081/render
  GF_RENDERING_CALLBACK_URL: http://grafana-service:3000/
  GF_LOG_FILTERS: rendering:debug
