apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-image-renderer
  namespace: grafana-ns
  labels:
    app.kubernetes.io/name: grafana-image-renderer
    app.kubernetes.io/component: renderer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana-image-renderer
      app.kubernetes.io/component: renderer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana-image-renderer
        app.kubernetes.io/component: renderer
    spec:
      containers:
        - name: grafana-image-renderer
          image: grafana/grafana-image-renderer:3.0.1
          ports:
            - name: renderer
              containerPort: 8081

